### ISSUE TITLE
TypeError: Invalid URL  at new URL

### ISSUE THREAD

**Issue by artiark** [EmptyDreams/hexo-swpp#4]
hexo-swpp 版本为 3.3.7, swpp-backends版本为2.3.12。

在执行 `hexo-swpp -build` 时会报错：

```bash
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at eachAllLinkInUrl (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:254:52)
    at C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:413:51
    at Array.map (<anonymous>)
    at Object.eachAllLinkInCss [as handle] (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:413:41)
    at C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:84:27
    at eachAllFile (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:129:15)
    at C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:132:43
    at Array.map (<anonymous>)
    at eachAllFile (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:132:33)
    at C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:132:43
    at Array.map (<anonymous>)
    at eachAllFile (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:132:33)
    at Object.buildVersionJson (C:\Users\Administrator\Desktop\blog-source\node_modules\swpp-backends\dist\FileAnalyzer.js:64:11)
    at buildVersionJson (C:\Users\Administrator\Desktop\blog-source\node_modules\hexo-swpp\dist\index.js:175:56)
    at runSwpp (C:\Users\Administrator\Desktop\blog-source\node_modules\hexo-swpp\dist\index.js:112:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Hexo.<anonymous> (C:\Users\Administrator\Desktop\blog-source\node_modules\hexo-swpp\dist\index.js:88:13)
```

`sw-rules` 如下：
```commonjs
module.exports.ejectValues = (hexo, _) => {
    return {
        domain: {
            prefix: 'const',
            value: new URL(hexo.config.url).host
        }
    }
}

module.exports.config = {
    serviceWorker: {
        escape: 1,
        cacheName: 'mylhfBlogCache',
        debug: false
    },
    register: {
        onsuccess: () => console.log('Service Worker 注册成功！'),
        onerror: () => console.error('Service Worker 注册失败！可能是由于您的浏览器不支持该功能！'),
        /**
         * 生成注册 SW 的 HTML 代码片段
         * @param root {string} 网页根目录的 URL
         * @param hexoConfig {Object} Hexo 配置项
         * @param pluginConfig {Object} SW 配置项
         * @return {string} 一个 HTML 标签的字符串形式
         */
        builder: (root, hexoConfig, pluginConfig) => {
            const {onerror, onsuccess} = pluginConfig.register
            return `<script>
                      (() => {
                          const sw = navigator.serviceWorker
                          const error = ${onerror.toString()}
                          if (!sw?.register('/sw.js')
                              ${onsuccess ? '?.then(' + onsuccess + ')' : ''}
                              ?.catch(error)
                              ) error()
                      })()
                  </script>`
        }
    },
    dom: { onsuccess: () => {} },
    json: {
        maxHtml: 20,
        charLimit: 1024,
        merge: [],
        stable: [],
    },
    external: {
        timeout: 10000,
        concurrencyLimit: 10,
    }
}

/** 缓存列表 */
module.exports.cacheRules = {
    simple: {
      clean: true,
      match: (url, $eject) => {
        const allowedHost = $eject.domain;
        const allowedPaths = ["/404.html", "/css/index.css"];
        return url.host === allowedHost && allowedPaths.includes(url.pathname);
      },
    },
    cdn: {
      clean: true,
      match: url =>
        [
          "cdn.cbd.int",
          "cdn.staticfile.org",
          "npm.elemecdn.com",
          "cdn.jsdmirror.com",
          "npm.onmicrosoft.cn",
          "cdnjs.onmicrosoft.cn",
          "cdnjs.snrat.com",
          "s4.zstatic.net",
          "jsd.cdn.zzko.cn",
          "ai.tianli0.top",
          "cdn.luogu.com",
          "blog.lhf.us.kg",
          "wmimg.com",
          "cdn-hw-static.shanhutech.cn",
          "pic.imgdb.cn"
      ].includes(url.host) && url.pathname.match(/\.(js|css|woff2|woff|ttf|cur|webp)$/),
    }
}

module.exports.getRaceUrls = srcUrl => {
    if (srcUrl.startsWith('https://cdn.jsdelivr.net')) {
        const url = new URL(srcUrl)
        return [
            `https://gcore.jsdelivr.net` + url.pathname,
            `https://cdn.jsdmirror.com` + url.pathname
        ]
    }
    if (srcUrl.startsWith('https://gcore.jsdelivr.net')) {
        const url = new URL(srcUrl)
        return [
            `https://gcore.jsdelivr.net` + url.pathname,
            `https://cdn.jsdmirror.com` + url.pathname
        ]
    }
    if (srcUrl.startsWith('https://pic.imgdb.cn')) {
        const url = new URL(srcUrl)
        return [
            `https://pic.imgdb.cn` + url.pathname
        ]
    }
    if (srcUrl.startsWith('https://cdn.cbd.int')) {
        const url = new URL(srcUrl)
        return [
            srcUrl,
            `https://cdn.jsdmirror.com/npm` + url.pathname
        ]
    }
}

module.exports.custom = {
    flag: {
        type: true,
        value: false
    }
}

module.exports.skipRequest = request => request.url.startsWith('https://cdn.bootcss.com/KaTeX/0.11.1/katex.min.css')
module.exports.skipRequest = request => request.url.startsWith('https://cdn.jsdmirror.cn')
module.exports.skipRequest = request => request.url.startsWith('https://cdn.jsdmirror.com')

```

**Comment by EmptyDreams** [comment]
v2 已经停止维护，建议切换到 v3
